const { Router } = require("express");
const reviewRouter = require("./review/review.router");
const promptMobileRouter = require("./ai-integration/mobile-specification/prompt.mobile.routes");
const mobileSpecificationRouter = require("./mobile-specification/mobile.specification.routes");
const mobileProfileKywordRoutes = require("./mobile-specification/mobile.profilekeyword.routes");
const mobileFaqRouter = require("./mobile-specification/mobile.faq.routes");
const mysteryboxRouter = Router();
mysteryboxRouter.use(reviewRouter);
mysteryboxRouter.use(promptMobileRouter);
mysteryboxRouter.use(mobileSpecificationRouter);
mysteryboxRouter.use(mobileProfileKywordRoutes);
mysteryboxRouter.use(mobileFaqRouter);
module.exports = mysteryboxRouter;
