version: '3.8'
services:
  mongo-users:
    image: mongo
    ports:
      - "27017:27017"

  mongo-products:
    image: mongo
    ports:
      - "27018:27017"

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
    depends_on:
      - mongo-users
    environment:
      - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj

  product-service:
    build: ./product-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo-products
    environment:
      - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj

  android-application-service:
    build: ./android-application-service
    ports:
      - "8001:8001"
    depends_on:
      - mongo-users
      - product-service
    environment:
      - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj
