version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/users
      # - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj
      - RABBITMQ_URL=amqp://cybercraft:cybercraft@195.35.32.241:5672/

  product-service:
    build: ./product-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/products
      # - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj
      - RABBITMQ_URL=amqp://cybercraft:cybercraft@195.35.32.241:5672/

  # android 1 service
  android-1-service:
    build: ./android-application/android-1-service
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/android-1
      # - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj
      - RABBITMQ_URL=amqp://cybercraft:cybercraft@195.35.32.241:5672/

  # auth service 
  auth-service:
    build: ./auth-service
    ports:
      - "8003:8003"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/mystery-auth
      # - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj
      - RABBITMQ_URL=amqp://cybercraft:cybercraft@195.35.32.241:5672/

  # mobile service
  mobile-1-service:
    # build: ./mobile-service
    build: ./mobile-specifications/mobile-1-service
    ports:
      - "8004:8004" #Port 8004 is already in use, so we switch to 8007.
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/mobile-1
      # - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj
      - RABBITMQ_URL=amqp://cybercraft:cybercraft@195.35.32.241:5672/
  # mystery box service    
  mysterybox-service:
    build: ./mysterybox-service
    ports:
      - "8005:8005"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/mystery-box
      # - RABBITMQ_URL=amqps://zyhofqvj:cUzKnldbzpfhkWMvlK4-tIKUzJNG4kdE@kangaroo.rmq.cloudamqp.com/zyhofqvj
      - RABBITMQ_URL=amqp://cybercraft:cybercraft@195.35.32.241:5672/

volumes:
  mongo-data:
